name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  github-token:
    description: 'The github token needed to authenticate'
    required: true
  user:
    description: 'The user to notify'
    required: true
  label:
    description: 'The label to monitor'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
